### ISSUE TITLE
Always return "The video download link for this post is not available"

### ISSUE THREAD

**Issue by galihmrd** [riad-azz/instagram-video-downloader#2]
![Screenshot_2023-05-11-04-44-53-295_com android chrome](https://github.com/riad-azz/instagram-video-downloader/assets/69835093/6773a2f4-e990-44f8-ad22-e40934fdc4bf)

**Comment by riad-azz** [comment]
This is not an issue really, its because Vercel runs on serverless and the session gets suspended by Instagram since its considered as suspicious login because every time its used from a different region.
If you host the website on your own cloud instance you wont be getting this problem.

**Comment by riad-azz** [comment]
I updated the environment variables for more session cookie identifiers and added device identifier, account identifier, location identifier which should reduce suspicious behavior suspension by Instagram.

**Comment by HappySinha** [comment]
I'm facing the same errors when I host on vercel https://instagram-video-downloader-1.vercel.app/

**Comment by riad-azz** [comment]
The Authenticated API with cookie was removed duo to the high chance of being banned by Instagram because its against their terms of service.

As for the response "The video download link for this post is not available." is not an error or issue, it just means the scraper was not able to find the video URL on the post page.

![Untitled](https://github.com/riad-azz/instagram-video-downloader/assets/80968727/e225a3b4-84a6-4037-a40a-665813f10474)

If you want to use this app in production you will have to use [yt-dlp](https://github.com/yt-dlp/yt-dlp) to host a backend python server that fetches and serves the posts to the frontend. I did not implement this here because its not possible to host it on a serverless hosting like Vercel.

have a good day.

**Comment by riad-azz** [comment]
Also i noticed that you pushed your Auth cookie and Upstash info to the Github repository that you forked:

![image](https://github.com/riad-azz/instagram-video-downloader/assets/80968727/28b07037-b444-4888-8380-56b098ac5ac0)

Please make sure to change your password on Instagram and Upstash because people can use this info to access your account and never push `.env` files to the repository because all the variables there should be kept secret from everyone for security reasons.

Have a nice day.

**Comment by HappySinha** [comment]
Thank you so much for giving answere
