### ISSUE TITLE
is it possible to extend this app to support downloading reels ? 

### ISSUE THREAD

**Issue by drwiiche** [riad-azz/instagram-video-downloader#6]
**Question**
is it possible to extend this app to support downloading reels ?

**Comment by riad-azz** [comment]
The app does download reels if the video URL is public, but yeah you can extend the app further more and add more methods to downloading the reels or posts. By going to `src/lib/instagram/instagramAPI.ts` and adding whatever new method you would like then calling the function at the end of the file here :

![image](https://github.com/riad-azz/instagram-video-downloader/assets/80968727/1788c06d-669a-4a2c-9fe1-fe0e5ef54e1f)

**Comment by drwiiche** [comment]
your app looks great, good work
can you try for example to download this reel https://www.instagram.com/reels/Cw08igxNkzJ/

**Comment by riad-azz** [comment]
Hey  there again drwiiche,

The app does include downloading reels but only ones with public video url embded in the post page as mentioned in another issue answer here https://github.com/riad-azz/instagram-video-downloader/issues/7#issuecomment-1719205721

you will have to add your own implementation or API to fetch the video URL, my app doesn't have it included because Vercel serverless could not support a python backend and the website is just to preview the repository & i don't want to pay for hosting a python backend. I hope this clarified things.

have a good day.
