### ISSUE TITLE
Deployed Application is not working  

### ISSUE THREAD

**Issue by ankitbourasi0** [riad-azz/instagram-video-downloader#7]
**Describe the bug**
The Deployed application is not working on this link https://insta-video-saver.vercel.app/

**To Reproduce**
1. Go to: https://insta-video-saver.vercel.app/
2. Paste any Instagram reel link
3. Click on download Button
4. See Error

**Expected behavior**
Application should download the reel video and show the download alert box, after click on download button

**Screenshots**

https://github.com/riad-azz/instagram-video-downloader/assets/34002165/10710ca3-4bad-4955-8b1f-4887d5c8fa6c

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by riad-azz** [comment]
Hi there,

Thank you for taking the time to report this issue. I've looked into the problem you described, and I'd like to clarify a few points:

- Issue Repetition: This issue has been mentioned before in https://github.com/riad-azz/instagram-video-downloader/issues/2#issue-1704670597 and https://github.com/riad-azz/instagram-video-downloader/issues/5#issue-1842485271 The application is designed to download videos from Instagram posts that contain the video link directly on the page.

- Expected Behavior: As mentioned above, the application is intended to work with specific types of Instagram posts. When it encounters a valid post with the video link embedded in the page, it should download the video else it shows the error you provided.

However, you can add your own API implementation or scraping strategy in `src/lib/instagram/index.ts` to fetch the video link using something like [yt-dlp](https://github.com/yt-dlp/yt-dlp) as a backend.

Have a good day.
